name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions üöÄ
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # You can test your matrix by printing the current Python version
      # it is not possible to use `poetry shell`in an non-interactive env (https://github.com/orgs/python-poetry/discussions/3526)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry=="1.7.1"
          poetry install -vvv --no-cache
          source $(poetry env info --path)/bin/activate
      - name: Lint in libs/tools
        run: poetry run lint
      - name: Running tests with
        run: |
          python -m pip install coverage
          python -m pip install pytest
          coverage run -m pytest
      - name: Create report and badge
        run: |
          coverage xml
          pip install genbadge"[all]"
          genbadge coverage -i coverage.xml 
      - run: echo "üçè This job's status is ${{ job.status }}."
